"""API subsystem - FastAPI WebSocket server for UE5 bridge."""

from seaman_brain.api.protocol import (
    PROTOCOL_VERSION,
    BrainStateSnapshot,
    CreatureStateSnapshot,
    ErrorMessage,
    EventNotification,
    EventSeverity,
    InputMessage,
    MessageType,
    NeedsSnapshot,
    ResponseMessage,
    StateUpdate,
    TankSnapshot,
    TraitsSnapshot,
    check_protocol_version,
    parse_client_message,
    serialize_response,
)
from seaman_brain.api.server import BrainServer
from seaman_brain.api.streaming import (
    ALL_CHANNELS,
    ClientSubscription,
    EventBroadcaster,
    EventChannel,
    compute_state_diff,
    diff_to_channels,
)

__all__ = [
    "ALL_CHANNELS",
    "BrainServer",
    "ClientSubscription",
    "EventBroadcaster",
    "EventChannel",
    "PROTOCOL_VERSION",
    "BrainStateSnapshot",
    "CreatureStateSnapshot",
    "ErrorMessage",
    "EventNotification",
    "EventSeverity",
    "InputMessage",
    "MessageType",
    "NeedsSnapshot",
    "ResponseMessage",
    "StateUpdate",
    "TankSnapshot",
    "TraitsSnapshot",
    "check_protocol_version",
    "compute_state_diff",
    "diff_to_channels",
    "parse_client_message",
    "serialize_response",
]
